let g:UltiSnipsExpandTrigger="<tab>"                                            
let g:UltiSnipsJumpForwardTrigger="<tab>"                                       
let g:UltiSnipsJumpBackwardTrigger="<s-tab>" 
" let g:UltiSnipsSnippetsDir="/home/dclong/btsync/config/linux/common/vim/my_snippets"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"] 
" let g:UltiSnipsListSnippets="<c-tab>"
let g:UltiSnipsEditSplit="horizontal"
let g:UltiSnipsListSnippets="<c-l>" 
let g:ultisnips_python_style="doxygen"
